# Generated by Django 4.2 on 2023-07-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roompassword',
            field=models.CharField(default=123, max_length=1000),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomname',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
