# Generated by Django 4.2 on 2023-07-26 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_room_roompassword_alter_room_roomname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='posttime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
